# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-18 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthsinauser',
            name='openid',
        ),
        migrations.AddField(
            model_name='oauthsinauser',
            name='uid',
            field=models.CharField(db_index=True, default=0, max_length=64, verbose_name='access_token'),
            preserve_default=False,
        ),
    ]
