# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-12 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsvisitcount',
            name='category',
        ),
        migrations.DeleteModel(
            name='GoodsVisitCount',
        ),
    ]
